### ISSUE TITLE
Direct linking articles do not work in 1to1 tenant

### ISSUE THREAD

**Issue by sdubrick** [OneToOneService/iService-Forms#104] opened 2016-06-10 17:36 UTC
Direct linking works in qa.iservicecrm.com, but doesn't work in our 1to1service.iservicecrm.com tenant.  Please diagnose why it's not working.  Since we can't give you form editing access on this tenant, hopefully you can determine what the issue is and put a fix onto qa.iservicecrm.com, which we can test on 1to1service tenant for you.

Here is a direct link you can test on: https://1to1service.iservicecrm.com/f/customerportal-treeview#/find-answers?topicID=60&articleID=48650

**Comment by jaswantchouhan** [comment] 2016-06-11 12:47
#104 - i am not able to reproduce the issue in qa.iservicecrm.com, i have updated the code at 
https://qa.iservicecrm.com/f/122#/find-answers?topicID=7&articleID=1131 hope this will work

**Comment by sdubrick** [comment] 2016-06-11 15:08
@jaswantchouhan just a note, please please please make sure that you are always working from the latest commit.  We are having a real problem with changes being made on your end that regress other fixes.

**Comment by seani** [comment] 2016-06-11 15:11
Moved form 122 from qa tenant to form 118 in 1to1 tenant and it seems to work.
https://1to1service.iservicecrm.com/f/118#/find-answers?topicID=60&articleID=48650
Code checked into 7.4 branch.

**Closed as completed** 2016-06-11 16:40 UTC
Labels: bug, Customer Portal - Tree View (6650), Assigned
