### ISSUE TITLE
Occasionally click an item in Top FAQ loads No Article

### ISSUE THREAD

**Issue by scottwhitsitt** [OneToOneService/iService-Forms#52] opened 2016-02-12 20:28 UTC
If you click the 2nd link in the Top FAQ list, No Article is displayed in the article list. It is trying to load https://qa.iservicecrm.com/f/87#/find-answers?articleID=1374.

**Comment by sdubrick** [comment] 2016-02-15 16:19
cannot reproduce

**Comment by sdubrick** [comment] 2016-02-16 04:37
Supposedly thing can occasionally happen if the data fails to load.  However, I think this would be a network issue, and outside the scope of the application, so closing for now.

**Comment by sdubrick** [comment] 2016-02-17 17:02
Able to reproduce.. click across different FAQ items and it will randomly happen

**Comment by seani** [comment] 2016-02-17 20:07
The problem is that it's calling the `FindAnswerArticles` function multiple times simultaneously.  Add code before `ControllerFindAnswers`:

```
var articleListQueue = [];
var runningQueued = false;
function QueueArticleSearch(func) {
  if (runningQueued) {
    runningQueued = false;
    return false;
  }
  articleListQueue.push(func);
  if (articleListQueue.length > 1) {
    return true;
  }
  return false;
}
function FinishedArticleSearch() {
  articleListQueue.splice(0, 1);
  if (articleListQueue.length) {
    runningQueued = true;
    articleListQueue[0]();
  }
}
```

Change `function topfaq()`:

```
  function topfaq() {
    if (QueueArticleSearch(topfaq)) return;
    ...
    iservice.FindAnswerArticles(..., function (data) {
      ...
      $timeout(FinishedArticleSearch);
    });
  }    
```

Change : `$scope.ShowTopic`:

```
  $scope.ShowTopic = function (topic) {
    if (QueueArticleSearch(function () { $scope.ShowTopic(topic); })) return;
    ...
    $scope.Searching = iservice.FindAnswerArticles(..., function (data) {
      ...
      $timeout(FinishedArticleSearch);
    });
    ...
  }
```

Making this problem worse is that the controller function `ControllerFindAnswers` is being run twice when the page first loads, which means it's in fact doing the `topfaq()` function twice and ShowTopic twice.  The code changes above is a workaround for this double loading problem as well, but it's not good that it is doing double the number of required calls.

**Comment by seani** [comment] 2016-02-17 20:26
Get rid of `ng-controller="ControllerFindAnswers"` to stop the double instantiation of the controller.  `ShowTopic` is still being called twice though due to `$scope.test` being executed twice.  I'm not sure what `$scope.test` is or why it's being called twice.

**Comment by jaswantchouhan** [comment] 2016-02-18 04:11
i have used $scope.test to call the article list of first topic after
finishing the display of topic list. its only called onece when the topic
list rendering finish

**Comment by jaswantchouhan** [comment] 2016-02-18 04:29
calling twice the controller due to declaration in $routeProvider and dom
too

**Comment by jaswantchouhan** [comment] 2016-02-18 04:48
the reason behind calling it twice was calling the function inside loop, it
is fixed now

**Comment by sdubrick** [comment] 2016-02-18 05:57
since at least the bug isn't reproducible anymore i'm going to close it out.

**Closed as completed by sdubrick** 2016-02-18 05:57 UTC
Labels: bug, Customer Portal - Tree View (6650)
